name: first_workflow
on: [push]
jobs:
    runfirst_command:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: npm install
              run: npm install
              working-directory: GitHub/GitHubAction/Lending
            - name: run lint
              run: npm run lint
              working-directory: GitHub/GitHubAction/Lending
